version: "3"

services:


  postgres-db:
      container_name: postgres-db
      image: postgres
      environment:
        - POSTGRES_DB=db
        - POSTGRES_PASSWORD=pass
        - POSTGRES_USER=root
      ports:
        - 5555:5432
      restart: always


  redis:
      image: redis/redis-stack
      ports:
        - 6379:6379

  redis-insight:
      image: redislabs/redisinsight:latest
      ports:
        - 8001:8001




